[package]
name = "odra-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
# odra = { git = "https://github.com/odradev/odra", branch = "develop", default-features = false }
odra = { path = "../odra/core", default-features = false }


[features]
default = ["mock-vm"]
mock-vm = ["odra/mock-vm"]
wasm-test = ["odra/wasm-test"]
wasm = ["odra/wasm"]
