name = "owned_token_template"
[contracts]
owned_token = { path = "src/owned_token.rs", name = "owned_token", fqn = "owned_token_template::OwnedToken"}
erc20 = { path = "src/erc20.rs", name = "erc20", fqn = "owned_token_template::Erc20"}
ownable = { path = "src/ownable.rs", name = "ownable", fqn = "owned_token_template::Ownable"}
